spring:
  profiles:
    active: develop
  application:
    name: loan-cloud-eureka

server:
  port: 8761 #启动端口

---
spring:
  profiles: develop

eureka:
  client:
    registerWithEureka: false  #false:不作为一个客户端注册到注册中心
    fetchRegistry: false      #为true时，可以启动，但报异常：Cannot execute request on any known server

---
spring:
  profiles: test

eureka:
  client:
    registerWithEureka: false  #false:不作为一个客户端注册到注册中心
    fetchRegistry: false      #为true时，可以启动，但报异常：Cannot execute request on any known server
